sudo: enabled
dist: trusty
language: node_js
node_js:
- node
install:
- npm install
- npm test
notifications:
  slack:
    secure: fUtAhPlvjX3xvMGiIXQlm8ZoI5/D1EwOsyB37ClpJ0CGpFXwUK0CqCv67PHqCjJXm2k5jYP1+usLF5y5uJmT9on20DBsqOAfCTW8NZxhTXIXvYR3mF+e0rN3b1/qeDOvQEDs8QcnbwLE+xPgkWvmAhTX9KAFEDfUD/fGUAHfeXaDNhzwDcOs9idF9v6jvfgJfTBUYy5dQeN9a++MmEnibIJfKdJhZ4bL1KCwBPNIBIAdBBfeLosX/QD7APvNB2z0oSibrJTP1zGzgq6asH1QoxftWghT8lsGstFTYRWhUoXykrps6lRLz4zvk/QJgEnYNeloyhcjXg/gChku2O4wgaUhLJZ69R28LtKZ2ODECnjMbuq+I9bL6H781lqKb0Sn4lIb4ek3k/nf+eEJnfABUMomjhx0JNAFsmsV0VOHQFZNt22MtEIjRC+EhrYYdO6v3yFGaKxqUhsb/y3DgCquxkb8TCGR2A1eZHpZiSGF63xHjbHUs6T5iSQYmeQZohyJsu224dMezD37uPO+OgsEcgpHRN1cpfUhMoiFv77iyczGMRrZu51+2wnGBciupigCdiSf15r5dHLepD46rlOR1aYPU9aqWasAjUSNxMkqw1EWDKeDbdOWjhKhEeN0uyYunOMR5/lpnSBQ+sAGhZlpXDO84o1hKFcksdrtcqjJXyk=
