sudo: enabled
dist: trusty
language: node_js
node_js:
- "lts/*"
services:
- mongodb
before_script:
  - sleep 5
  - cd app
env:
  - MONGO_CONTAINER=localhost MONGO_PORT=27017 DB_NAME=lazyJar
script:
  - npm install && npm test