sudo: enabled
dist: trusty
language: node_js
node_js:
- node
install:
- npm install
- npm test
notifications:
  slack:
    secure: k4sWH0dsN+eDQN3V/KwqNYTVPamKZeDweuNgoKGdppOSfgsu+9nZOlqWcTQZtmhVDiNdMLFa2dH3DqQpWdRXnx2+gpg4coq5jVXez6r4y3/ktzirKrdWYuX6aOGxVy8lgmvKL3NJoqS73VVsXLiNRZokuzzNQxU1rARqCZE3WzTo/Volv3v2Y7z/QjGxgHSSZOBSouuHr8dUCPDNhIDQJJTYHGhWBIC9AZxLxqoiF5jir+lYDV2nPrK12hQUGGDO7BKwsCEBmD2DuVE73DSATkqi6Q+XgHWrcIyePIsjxsqa2fx3YcPaIVOO7/N1v+85FD9JvH7PywBkWsK8Wr86Ambc6wHccYmujwX7OnKKDcVD2Yu38tpHUw73z2Niek220WpxF2E1rwzR0zqLuxmlxptNa0JVxLFYOjJ3nai+8t3fP5rMp4OY4svnZImJGNPCkln8j9Qdm7MlFtbJjvAZxx8tlSwCpeRXLDzrM2uSzEDjKAn0ymnQNkWs735s69wK1lKrijCodbB7nlHffJbkH67354hqkfJCY5pS5G8unCrIheUpAXXpvGaYj3R9buZwl4wk7jUoaGDtMWSICgQC1jU6jSbT7eBjirKIR58rV2CyWIVi1C7Ig6tXDiAxUwkb+++91bi05PI7s5OtGiMqn3pz24yZq4UnejJqvgAfq8U=
