sudo: enabled
dist: trusty
language: node_js
node_js: "lts/*"
services:
- mongodb
before_script:
- sleep 5
- cd ${TRAVIS_BUILD_DIR}/app
env:
- MONGO_CONTAINER=localhost MONGO_PORT=27017 DB_NAME=lazyJar CLOUD_SDK_REPO=cloud-sdk-trusty
script:
- npm install && npm test
before_install:
- cd ${TRAVIS_BUILD_DIR}
- openssl aes-256-cbc -K $encrypted_a8e9febd254e_key -iv $encrypted_a8e9febd254e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- chmod +x  ${TRAVIS_BUILD_DIR}/scripts/deploy.sh
before_deploy:
- echo 1
- mv ${TRAVIS_BUILD_DIR}/secrets/mongo/mongo.key.json ${TRAVIS_BUILD_DIR}/mongo/
- echo 2
- mv ${TRAVIS_BUILD_DIR}/secrets/deploy.key.json ${TRAVIS_BUILD_DIR}
- echo 3
- echo "deb http://packages.cloud.google.com/apt cloud-sdk-trusty main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- sudo curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install -y google-cloud-sdk 
- sudo apt-get autoremove && sudo apt-get clean
- echo 4
deploy:
- provider: script
  script: "${TRAVIS_BUILD_DIR}/scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: docker
    