sudo: enabled
dist: trusty
language: node_js
node_js:
- node
install:
- npm install
- npm test
notifications:
  slack:
    secure: Vez6xvKrMr6GA8hWeCI9ztmJkl2YlUn4p/uA0JiTecS5aSPNnyOZ85m70V9l6ZIPKVl48v5+zs9DDSYqSC2SEZ0dx3yzJIxxeSzeMvz8iw4OD0aap7xtxCtIMkekBCqu1QqMQoTDkSMcWhx7HRvTxNT3rn1Co5JVAuUn8PkrnaWOf0GzcFUTW32f3+67pfHxt3ypB0A0jWVTgLCOTVg/dU9AJWBQcB1HYxHHQKK88dNEYUXPinzfDMH7Fu5Ncj545pSamaDvuLrp5He6+o9PbzZLU45pkNS91SasHTSj0dO8zoqeHW05DtDjTb/yRl3S0DVNnySP57sIJssI3OYRGXaFdE9UfgbtcXJuABM09feCX7r1/zwbawZNR14AN6gAsXjVtRcW66nfg0cGcb0LxaIDEr/FZ7eQCBkiGND59jfYUeoW/GZnY48v+QHP1VWMAmUs5vcl+tTRWEpAdd/OhigtSV+JrXZtxPtuxZyhWmaN1PWj2vBMda80ZOASAfKR/xwO8wb/KytHMD7nGlb4Ri3wAkSLjTlx5c8HyAdH7kotsI5lxPoeydnp12zltMr7xFjbuSSmO03BGVgl+Z/x9KITpv0gqMeaueq6btPKfY+Z+ppRv0useI32bjvcswKpIQCSfA4aqbr+yZf7RSazJKMiGdxTcxcyfaWImgDpugM=